<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="r200" params="name parent *origin">

    <xacro:property name="r200_cam_rgb_px" value="0.005"/>
    <xacro:property name="r200_cam_rgb_py" value="0.018"/>
    <xacro:property name="r200_cam_rgb_pz" value="0.013"/>
    <xacro:property name="r200_cam_depth_offset" value="0.01"/>

    <joint name="${name}_joint" type="fixed">
        <xacro:insert_block name="origin"/>
        <parent link="${parent}"/>
        <child link="${name}_link"/>
    </joint>

    <link name="${name}_link">
        <visual>
            <origin xyz="0 0 0" rpy="1.57 0 1.57"/>
            <geometry>
                <mesh filename="package://turtlebot3_beam_description/meshes/sensors/r200.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.003 0.065 0.007" rpy="0 0 0"/>
            <geometry>
                <box size="0.012 0.132 0.020"/>
            </geometry>
        </collision>
    </link>

    <joint name="${name}_rgb_joint" type="fixed">
        <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
        <parent link="${name}_link"/>
        <child link="${name}_rgb_frame"/>
    </joint>
    <link name="${name}_rgb_frame"/>

    <joint name="${name}_rgb_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
        <parent link="${name}_rgb_frame"/>
        <child link="${name}_rgb_optical_frame"/>
    </joint>
    <link name="${name}_rgb_optical_frame"/>

    <joint name="${name}_depth_joint" type="fixed">
        <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py + r200_cam_depth_offset} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
        <parent link="${name}_link"/>
        <child link="${name}_depth_frame"/>
    </joint>
    <link name="${name}_depth_frame"/>

    <joint name="${name}_depth_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
        <parent link="${name}_depth_frame"/>
        <child link="${name}_depth_optical_frame"/>
    </joint>
    <link name="${name}_depth_optical_frame"/>

    <gazebo reference="${name}_link">
        <sensor type="depth" name="realsense_R200">
            <always_on>true</always_on>
            <update_rate>15.0</update_rate>
            <visualize>false</visualize>
            <camera>
                <horizontal_fov>1.3439</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>360</height>
                    <format>R8G8B8</format>
                </image>
                <depth_camera></depth_camera>
                <clip>
                    <near>0.03</near>
                    <far>100</far>
                </clip>
                <distortion>
                    <k1>0.0</k1>
                    <k2>0.0</k2>
                    <k3>0.0</k3>
                    <p1>0.0</p1>
                    <p2>0.0</p2>
                    <center>0.5 0.5</center>
                </distortion>
            </camera>
            <plugin name="camera_controller_${name}" filename="libgazebo_ros_camera.so">
                <baseline>0.2</baseline>
                <camera_name>${name}</camera_name>
                <frame_name>${name}_rgb_optical_frame</frame_name>
                <ros>
                    <remapping>${name}/image_raw:=${name}/rgb/image_raw</remapping>
                    <remapping>${name}/depth/image_raw:=${name}/depth/image_raw</remapping>
                    <remapping>${name}/camera_info:=${name}/rgb/camera_info</remapping>
                    <remapping>${name}/depth/camera_info:=${name}/depth/camera_info</remapping>
                </ros>
                <min_depth>0.4</min_depth>
                <hack_baseline>0.07</hack_baseline>
                <focal_length>0</focal_length>
            </plugin>
        </sensor>
    </gazebo>
  </xacro:macro>

</robot>
